version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && make start"
    volumes:
      - .:/diary_development
      - .:/diary
    ports:
      - '3000:3001'
    depends_on:
      - db
