version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:reset && RAILS_ENV=test bundle exec rails db:schema:load RAILS_ENV=test && bundle exec rails db:migrate RAILS_ENV=test foreman start -f Procfile.test -p 3000"
    volumes:
      - .:/diary_test
      - .:/diary
    ports:
      - '3000:3000'
    depends_on:
      - db
